//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class empTable01
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public Nullable<int> addressid { get; set; }
        public Nullable<int> empid { get; set; }
    
        public virtual empTable02 empTable02 { get; set; }
    }
}
